


//order save
export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST';

export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS';

export const ORDER_SAVE_FAIL = 'ORDER_SAVE_FAIL';



//order list
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';

export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';

export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';




//order detail
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';

export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';

export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';



//order delete
export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';

export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';

export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';


// user order list
export const USERORDER_LIST_REQUEST = 'USERORDER_LIST_REQUEST';

export const USERORDER_LIST_SUCCESS = 'USERORDER_LIST_SUCCESS';

export const USERORDER_LIST_FAIL = 'USERORDER_LIST_FAIL';



//user order retails
export const USERORDER_DETAIL_REQUEST = 'USERORDER_LIST_REQUEST';

export const USERORDER_DETAIL_SUCCESS = 'USERORDER_LIST_SUCCESS';

export const USERORDER_DETAIL_FAIL = 'USERORDER_LIST_FAIL';




