
//list product
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';


export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';


//save product
export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';

export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';

export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';



//delete product
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_SAVE_REQUEST';

export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';

export const PRODUCT_DELETE_FAIL = 'PRODUCT_SAVE_FAIL';



//detail priduct
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';

export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';


export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

